-- ============================================================
-- DEMO ENVIRONMENT DATA REFERENCE
-- ============================================================
-- 
-- ⚠️  DO NOT RUN THIS FILE DIRECTLY IN PRODUCTION ⚠️
--
-- This file is for DOCUMENTATION purposes only.
-- It shows the structure and content of the demo environment.
--
-- To seed demo data, use the Edge Function approach:
-- POST /functions/v1/seed-demo-classroom
--
-- Why Edge Function instead of SQL:
-- 1. Cannot directly manipulate auth.users (requires Auth API)
-- 2. Edge Function uses service role for cross-table operations
-- 3. Can trigger analysis functions automatically
-- 4. Better error handling and rollback
-- 5. Returns structured response with credentials
-- 6. CORS-enabled for frontend calls
--
-- ============================================================

-- DEMO TEACHER PROFILE
-- ------------------------------------------------------------
-- Teacher Profile Structure (created by Edge Function)
SELECT 
  'demo_teacher_001' as id,
  'demo_teacher_001' as user_id,
  'Lincoln Elementary School' as school_name,
  ARRAY['5']::text[] as grade_levels,
  ARRAY['Science']::text[] as subjects,
  8 as years_experience,
  true as onboarding_completed;

-- DEMO CLASS
-- ------------------------------------------------------------
SELECT 
  'demo_class_001' as id,
  'demo_teacher_001' as teacher_id,
  '5th Grade Science - Room 204' as name,
  'Science' as subject,
  '5' as grade_level,
  true as published,
  'active' as status;

-- DEMO STUDENTS (15 students with varied performance levels)
-- ------------------------------------------------------------
-- Advanced Level (3 students)
SELECT 'demo_student_001' as id, 'Emma' as first_name, 'Rodriguez' as last_name, '5' as grade_level
UNION ALL SELECT 'demo_student_002', 'Marcus', 'Chen', '5'
UNION ALL SELECT 'demo_student_003', 'Aisha', 'Patel', '5'

-- Proficient Level (5 students)
UNION ALL SELECT 'demo_student_004', 'Jake', 'Wilson', '5'
UNION ALL SELECT 'demo_student_005', 'Sofia', 'Martinez', '5'
UNION ALL SELECT 'demo_student_006', 'Tyler', 'Anderson', '5'
UNION ALL SELECT 'demo_student_007', 'Maya', 'Johnson', '5'
UNION ALL SELECT 'demo_student_008', 'Ethan', 'Brown', '5'

-- Developing Level (5 students)
UNION ALL SELECT 'demo_student_009', 'Olivia', 'Davis', '5'
UNION ALL SELECT 'demo_student_010', 'Noah', 'Garcia', '5'
UNION ALL SELECT 'demo_student_011', 'Isabella', 'Lee', '5'
UNION ALL SELECT 'demo_student_012', 'Liam', 'Taylor', '5'
UNION ALL SELECT 'demo_student_013', 'Ava', 'White', '5'

-- Emerging Level (2 students)
UNION ALL SELECT 'demo_student_014', 'Mia', 'Martinez', '5'
UNION ALL SELECT 'demo_student_015', 'Lucas', 'Anderson', '5';

-- DEMO ASSIGNMENTS
-- ------------------------------------------------------------
SELECT 
  'demo_assignment_001' as id,
  'demo_class_001' as class_id,
  'Photosynthesis Explanation' as title,
  'Explain how plants make food from sunlight' as description,
  'Explain how plants make food from sunlight. Include the inputs (what goes in), the process (what happens), and the outputs (what comes out). Use at least 3 scientific terms in your explanation.' as instructions,
  100 as max_points,
  'Scientific Explanation Rubric:
  - Identifies Key Process (4 pts)
  - Names Components (4 pts)
  - Explains Mechanism (4 pts)
  - Uses Scientific Vocabulary (4 pts)' as rubric
UNION ALL
SELECT 
  'demo_assignment_002',
  'demo_class_001',
  'Water Cycle Diagram',
  'Draw and label the water cycle',
  'Create a diagram showing evaporation, condensation, precipitation, and collection.',
  100,
  NULL
UNION ALL
SELECT 
  'demo_assignment_003',
  'demo_class_001',
  'Ecosystem Interactions',
  'Describe predator-prey relationships',
  'Choose an ecosystem and explain how predators and prey interact.',
  100,
  NULL;

-- SAMPLE SUBMISSION STRUCTURE
-- ------------------------------------------------------------
-- Advanced Level Example
SELECT 
  'demo_submission_001' as id,
  'demo_student_001' as user_id,
  'demo_assignment_001' as assignment_id,
  'Photosynthesis is the process where plants convert light energy into chemical energy. 
   The inputs are carbon dioxide (CO2) from the air, water (H2O) from the roots, and sunlight energy.
   Inside the chloroplasts, specifically in the chlorophyll, light energy breaks apart water molecules
   in a process called photolysis. This releases oxygen as a byproduct. The plant then uses the hydrogen
   from water and carbon from CO2 to create glucose (C6H12O6), which is stored energy. The outputs are
   glucose for the plant''s food and oxygen that we breathe. This process happens in two stages:
   light-dependent reactions and the Calvin cycle.' as text_response,
  'submitted' as status;

-- SUBMISSION ANALYSIS STRUCTURE (Generated by analyze-submission function)
-- ------------------------------------------------------------
SELECT 
  gen_random_uuid() as id,
  'demo_submission_001' as submission_id,
  'advanced' as mastery_level,
  92 as overall_score,
  'Excellent explanation with comprehensive scientific vocabulary' as feedback_summary,
  jsonb_build_object(
    'strengths', ARRAY[
      'Accurate identification of inputs and outputs',
      'Clear explanation of photolysis and glucose formation',
      'Correct use of chemical formulas',
      'Mentions both stages (light-dependent and Calvin cycle)'
    ],
    'areas_for_growth', ARRAY[
      'Could add more detail about chloroplast structure',
      'Consider explaining the role of ATP and NADPH'
    ],
    'next_steps', ARRAY[
      'Explore cellular respiration as complementary process',
      'Research limiting factors in photosynthesis'
    ]
  ) as analysis_details;

-- ============================================================
-- SEEDING INSTRUCTIONS
-- ============================================================
--
-- TO SEED DEMO DATA:
-- ------------------
-- 1. Use the Edge Function endpoint:
--    POST https://irxzpsvzlihqitlicoql.supabase.co/functions/v1/seed-demo-classroom
--    Body: { "reset": false }
--
-- 2. Or use the frontend UI:
--    Navigate to /demo/adaptive-classroom
--    Click "Seed Demo Data" button
--
-- 3. Or use the React hook:
--    import { useSeedDemoEnvironment } from '@/hooks/useSeedDemoEnvironment'
--    const { mutate: seedDemo } = useSeedDemoEnvironment()
--    seedDemo()
--
-- TO RESET DEMO DATA:
-- -------------------
-- POST https://irxzpsvzlihqitlicoql.supabase.co/functions/v1/seed-demo-classroom
-- Body: { "reset": true }
--
-- This will delete existing demo data and recreate everything.
--
-- ============================================================
-- DEMO CREDENTIALS (Generated by Edge Function)
-- ============================================================
--
-- Teacher Account:
-- Email: demo.teacher@tailoredu.local
-- Password: DemoTeacher2024!
-- User ID: demo_teacher_001
--
-- Student Accounts: demo_student_001 through demo_student_015
-- Email Pattern: demo.student.{001-015}@tailoredu.local
-- Password: DemoStudent2024!
--
-- ⚠️  These are temporary demo accounts and should not be used
--     in production environments.
--
-- ============================================================
