// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irxzpsvzlihqitlicoql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeHpwc3Z6bGlocWl0bGljb3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTEyMjIsImV4cCI6MjA2NjA4NzIyMn0.929IMktVJDlCZbuQYl57ipod6V96P3PcDxrCoLwrqCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);