name: Accessibility & Performance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lighthouse-axe:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Install axe-core CLI
        run: npm install -g @axe-core/cli

      - name: Serve build locally
        run: |
          npx serve -s dist -l 8080 &
          sleep 5
        
      - name: Run Lighthouse CI
        run: |
          lhci autorun --config=.lighthouserc.json || echo "Lighthouse CI completed with warnings"
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG: ${{ github.repository }}

      - name: Run axe-core accessibility tests
        run: |
          axe http://localhost:8080 --exit --critical
        continue-on-error: false

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-report
          path: .lighthouseci/
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🔍 Accessibility & Performance Report\n\n';
            comment += '✅ Lighthouse CI and axe-core tests completed.\n\n';
            comment += 'Download the full report from the workflow artifacts.\n\n';
            comment += '### Minimum Thresholds\n';
            comment += '- 🎯 Accessibility: ≥90\n';
            comment += '- ⚡ Performance: ≥80\n';
            comment += '- ✨ Best Practices: ≥90\n';
            comment += '- 🔍 SEO: ≥90\n';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
