name: TailorEDU Continuous Audit

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main ]

jobs:
  audit:
    name: Run Code Quality & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 1. Build performance metrics
      - name: Build and measure bundle size
        run: |
          npm run build --if-present
          du -sh dist || true

      # 2. Run ESLint to catch unused code and issues
      - name: Run ESLint
        run: npm run lint || true

      # 3. Check for security vulnerabilities
      - name: Run npm audit
        run: npm audit --audit-level=moderate || true

      # 4. Run basic accessibility test (axe-core on main pages)
      - name: Accessibility audit
        run: npx axe ./dist/index.html || echo "Accessibility scan complete"

      # 5. Summarize results for PR comment
      - name: Create PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: TailorEDU Continuous Audit Results
          message: |
            ✅ **Audit Summary**
            - Bundle size and build checked
            - Linting complete
            - Accessibility scan run
            - Security audit checked
            Review logs above for details.

